version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Build complete - Flask app ready for deployment"
  post_build:
    commands:
      - echo "Zipping artifact..."
      - zip -r flask-app.zip .
artifacts:
  files:
    - '**/*'

